version: "3.7"
services:
  react-prod:
    container_name: react-prod
    build:
      context: .
      dockerfile:
        Dockerfile.prod
    image: react-prod:latest
    ports:
      - "80:80"
      - "443:443"