version: "3.7"
services:
  react-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: ghcr.io/gnussonnet/dockerized-react-nginx:latest
    ports:
      - "80:80"
      - "443:443"