version: "3.7"
services:
  react-prod:
    container_name: dockerized-react-nginx
    build:
      context: .
      dockerfile:
        Dockerfile.prod
    image: react-app:latest
    ports:
      - "80:80"
      - "443:443"